# Generated by Django 4.0.3 on 2022-04-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='b',
        ),
        migrations.AddField(
            model_name='botuser',
            name='access_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='botuser',
            name='channel_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='botuser',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='botuser',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='botuser',
            name='user_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
