# Generated by Django 4.0.3 on 2022-04-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_botuser_b_botuser_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='smth_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
