# Generated by Django 4.0.3 on 2022-04-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_botuser_smth_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='channel_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='smth_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
