# Generated by Django 4.0.3 on 2022-04-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_botuser_response_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='extra_status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
