# Generated by Django 4.0.3 on 2022-04-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_botuser_extra_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=255)),
                ('user_id', models.CharField(default='', max_length=255)),
                ('user_type', models.CharField(default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('can_post_messages', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
