# Generated by Django 4.0.3 on 2022-04-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_channel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='Channels_info',
        ),
    ]
