# Generated by Django 4.0.3 on 2022-04-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_channel_channels_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='instagram_account_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
